### ISSUE TITLE
update_date in example_app is causes failure on the 29th, 30th, and 31st of any month

### ISSUE THREAD

**Issue by soundofjw** [Loudr/pale#12]
Tests are failing due to `update_date` in example app.

This is because of how `DateTimeModel` assumes a day when `update_date` is called:
```python
if day is None:
   day = self.timestamp.day
```

In the test, `self.timestamp` is utcnow, so it could be the 30th.
The tests try to update the month to February (2), which has no 29th, 30th, or 31st.

This highlights how it is not safe to assume a day of `None` when updating a `DateTimeModel`.

```python
ERROR: test_successful_post_with_required_params (tests.test_webapp2_adapter.Webapp2AdapterTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/josh/Development/pale/tests/test_flask_adapter.py", line 50, in test_successful_post_with_required_params
    resp = self.app.post('/api/time/parse', {'month': 2})
  File "/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webtest/app.py", line 370, in post
    content_type=content_type)
  File "/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webtest/app.py", line 735, in _gen_request
    expect_errors=expect_errors)
  File "/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webtest/app.py", line 631, in do_request
    self._check_status(status, res)
  File "/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webtest/app.py", line 663, in _check_status
    res)
AppError: Bad response: 500 Internal Server Error (not 200 OK or 3xx redirect for http://localhost/api/time/parse)
<html>
  <head>
    <title>Internal Server Error</title>
    <style>
      body {
        padding: 20px;
        font-family: arial, sans-serif;
        font-size: 14px;
      }
      pre {
        background: #F2F2F2;
        padding: 10px;
      }
    </style>
  </head>
  <body>
    <h1>Internal Server Error</h1>
    <p>The server has either erred or is incapable of performing
    the requested operation.</p>
    <pre>Traceback (most recent call last):
  File &quot;/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webapp2.py&quot;, line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File &quot;/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webapp2.py&quot;, line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File &quot;/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webapp2.py&quot;, line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File &quot;/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webapp2.py&quot;, line 1102, in __call__
    return handler.dispatch()
  File &quot;/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webapp2.py&quot;, line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File &quot;/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webapp2.py&quot;, line 570, in dispatch
    return method(*args, **kwargs)
  File &quot;/Users/josh/Development/pale/pale/adapters/webapp2.py&quot;, line 19, in pale_handler
    return pale_endpoint._execute(self.request)
  File &quot;/Users/josh/Development/pale/pale/endpoint.py&quot;, line 170, in _execute
    raise e
ValueError: day is out of range for month
</pre>
  </body>
</html>
-------------------- >> begin captured logging << --------------------
root: INFO: extracted endpoints: [<tests.example_app.api.endpoints.CurrentTimeEndpoint object at 0x106d0eb50>, <tests.example_app.api.endpoints.ParseTimeEndpoint object at 0x106d0ed50>, <tests.example_app.api.endpoints.TimeRangeEndpoint object at 0x106d10050>]
root: INFO: adding endpoint current_time to webapp!
root: INFO: current_time
root: INFO: created route: <Route('/api/time/current', <class 'pale.adapters.webapp2.current_time'>, name='current_time', defaults={}, build_only=False)>
root: INFO: adding endpoint parse_time to webapp!
root: INFO: parse_time
root: INFO: created route: <Route('/api/time/parse', <class 'pale.adapters.webapp2.parse_time'>, name='parse_time', defaults={}, build_only=False)>
root: INFO: adding endpoint time_range_now_plus_duration to webapp!
root: INFO: time_range_now_plus_duration
root: INFO: created route: <Route('/api/time/range', <class 'pale.adapters.webapp2.time_range_now_plus_duration'>, name='time_range_now_plus_duration', defaults={}, build_only=False)>
root: INFO: app router state: <Router([<Route('/api/time/current', <class 'pale.adapters.webapp2.current_time'>, name='current_time', defaults={}, build_only=False)>, <Route('/api/time/parse', <class 'pale.adapters.webapp2.parse_time'>, name='parse_time', defaults={}, build_only=False)>, <Route('/api/time/range', <class 'pale.adapters.webapp2.time_range_now_plus_duration'>, name='time_range_now_plus_duration', defaults={}, build_only=False)>])>
root: ERROR: day is out of range for month
root: ERROR: day is out of range for month
Traceback (most recent call last):
  File "/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Users/josh/Development/pale/venv/lib/python2.7/site-packages/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/Users/josh/Development/pale/pale/adapters/webapp2.py", line 19, in pale_handler
    return pale_endpoint._execute(self.request)
  File "/Users/josh/Development/pale/pale/endpoint.py", line 170, in _execute
    raise e
ValueError: day is out of range for month
```

**Comment by soundofjw** [comment]
@rknLA I've got the test passing again, but I'm sure you'll want to review this.
